apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: argocd-training-vpc
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 172.16.0.0/16
    tags:
      Name: ArgoCDTrainingVpc

